print('<<<welcome to python>>>')
print('Enter your name :')
name = input()
print('Enter your department :')
dept = input()
print('Enter your College')
college = input()
print('Enter your Percentage')
pc = input()

print('Name :'+' '+name)
print('department :'+' '+dept)
print('College :'+' '+college)
print('percentage :'+' '+pc)
